import { JobOpening, Candidate, Interview, Offer } from '../types';

/**
 * Recruitment Notification Service
 * 
 * This service acts as a scaffolding layer for triggering real notifications
 * (e.g., email, SMS, in-app alerts, Slack/Teams messages) based on recruitment events.
 * 
 * Future Backend Integration:
 * - Replace these mock implementations with actual API calls to a notification microservice.
 * - Ensure templates and localization are handled either here or on the backend.
 */
export const recruitmentNotificationService = {
  notifyOpeningSubmitted: async (opening: JobOpening, submitterId: string) => {
    console.log(`[NOTIFICATION] Job Opening ${opening.id} submitted by ${submitterId}. Notifying HR Managers.`);
    // TODO: Call backend API to trigger "Opening Pending Approval" email to HR Managers
  },

  notifyOpeningApproved: async (opening: JobOpening, approverId: string) => {
    console.log(`[NOTIFICATION] Job Opening ${opening.id} approved by ${approverId}. Notifying hiring team.`);
    // TODO: Call backend API to trigger "Opening Approved" email to the hiring team
  },

  notifyOpeningRejected: async (opening: JobOpening, rejectorId: string, reason: string) => {
    console.log(`[NOTIFICATION] Job Opening ${opening.id} rejected by ${rejectorId}. Reason: ${reason}`);
    // TODO: Call backend API to trigger "Opening Rejected" email to the submitter
  },

  notifyCandidateAdded: async (candidate: Candidate, adderId: string) => {
    console.log(`[NOTIFICATION] Candidate ${candidate.name} added by ${adderId} for Opening ${candidate.openingId}.`);
    // TODO: Call backend API to notify hiring manager
  },

  notifyCandidateRejected: async (candidate: Candidate, rejectorId: string, reason: string) => {
    console.log(`[NOTIFICATION] Candidate ${candidate.name} rejected by ${rejectorId}. Reason: ${reason}`);
    // TODO: Call backend API to send rejection email to candidate
  },

  notifyInterviewScheduled: async (interview: Interview, candidate: Candidate) => {
    console.log(`[NOTIFICATION] Interview ${interview.id} scheduled for Candidate ${candidate.name}.`);
    // TODO: Call backend API to send calendar invites to interviewers and the candidate
  },

  notifyOfferGenerated: async (offer: Offer, generatorId: string) => {
    console.log(`[NOTIFICATION] Offer ${offer.id} generated by ${generatorId}. Notifying approvers.`);
    // TODO: Call backend API to notify required approvers
  },

  notifyOfferSent: async (offer: Offer, candidate: Candidate) => {
    console.log(`[NOTIFICATION] Offer ${offer.id} sent to Candidate ${candidate.name} (${candidate.email}).`);
    // TODO: Call backend API to send the official offer email with a secure link to the candidate
  },

  notifyCandidateHired: async (candidate: Candidate, offer: Offer) => {
    console.log(`[NOTIFICATION] Candidate ${candidate.name} accepted Offer ${offer.id}. Notifying IT and HR.`);
    // TODO: Call backend API to trigger onboarding workflows (IT equipment, accounts, etc.)
  },

  notifyCandidateConverted: async (candidate: Candidate, employeeId: string) => {
    console.log(`[NOTIFICATION] Candidate ${candidate.name} converted to Employee ${employeeId}.`);
    // TODO: Call backend API to send welcome email to the new employee
  }
};
