import React, { useState } from 'react';
import { ShieldCheck, LockKeyhole } from 'lucide-react';
import { ROLE_ACCESS_POLICIES, ROLE_ORDER, ROLE_PROFILES } from '../modules/auth/permissions';
import { useAuth } from '../modules/auth/AuthContext';
import { useTranslation } from '../hooks/useTranslation';
import { RoleType } from '../types';

export const MODULE_NAMES: Record<string, [string, string]> = {
  '/': ['لوحة العمل', 'Workspace'], '/employees': ['الموظفون', 'Employees'], '/doctors': ['الأطباء', 'Doctors'], '/scheduling': ['المناوبات', 'Scheduling'], '/leaves': ['الإجازات', 'Leave'], '/attendance': ['الحضور', 'Attendance'], '/licenses': ['التراخيص', 'Credentials'], '/recruitment': ['التوظيف', 'Recruitment'], '/performance': ['الأداء', 'Performance'], '/payroll': ['الرواتب', 'Payroll'], '/health': ['الصحة المهنية', 'Occupational health'], '/reports': ['التقارير', 'Reports'], '/admin': ['إدارة النظام', 'Administration'], '/settings': ['الإعدادات', 'Settings'], '/profile': ['ملفي', 'My profile'], '/access': ['دليل الصلاحيات', 'Role access guide'],
};
export function RoleAccessPage() {
  const { user } = useAuth();
  const { language } = useTranslation();
  const ar = language === 'ar';
  const [selected, setSelected] = useState<RoleType>(user!.role);
  const profile = ROLE_PROFILES[selected];
  return <section className="space-y-6">
    <header><p className="text-sm text-brand-deep-teal font-semibold">REMEDIX / ACCESS GOVERNANCE</p><h1 className="text-3xl font-bold mt-2">{ar ? 'كل دور، بحدود واضحة' : 'Every role. Clear boundaries.'}</h1><p className="text-text-secondary mt-3">{ar ? 'السلطة التقنية والإدارية والمالية والصحية منفصلة. اختيار بطاقة هنا للشرح فقط ولا يغيّر حسابك.' : 'Technical, management, finance and health authority are separate. Selecting a card explains a role; it does not change your account.'}</p></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{ROLE_ORDER.map(role => <button key={role} onClick={() => setSelected(role)} aria-pressed={selected === role} className={`text-start rounded-xl p-4 border transition-colors ${selected === role ? 'bg-brand-deep-teal text-white border-brand-deep-teal' : 'bg-white border-border-base hover:border-brand-deep-teal'}`}><ShieldCheck size={20} className="mb-3"/><p className="font-semibold">{ar ? ROLE_PROFILES[role].ar : role}</p><p className="text-xs mt-2 opacity-75">{role === user!.role ? (ar ? 'دورك الحالي' : 'Your current role') : (ar ? 'عرض المسؤوليات' : 'View responsibilities')}</p></button>)}</div>
    <div className="grid gap-5 lg:grid-cols-3"><article className="card-base p-6 lg:col-span-1 space-y-5"><h2 className="text-xl font-bold">{ar ? profile.ar : selected}</h2><p className="font-semibold text-brand-deep-teal">{ar ? profile.authority : profile.en}</p>{ar && <p className="text-text-secondary leading-8">{profile.tasks}</p>}<div className="rounded-xl bg-bg-main p-4"><LockKeyhole size={20}/><h3 className="font-semibold my-2">{ar ? 'حدود الدور' : 'Boundaries'}</h3><p className="text-sm leading-7">{ar ? profile.limits : profile.en}</p></div></article>
    <article className="card-base p-6 lg:col-span-2"><h2 className="text-lg font-bold mb-4">{ar ? 'ما الذي يظهر له؟' : 'What can this role see?'}</h2><div className="overflow-auto"><table className="w-full text-sm text-start"><thead><tr className="text-text-secondary border-b border-border-base">{(ar ? ['القسم','نوع الوصول','النطاق'] : ['Module','Access','Scope']).map(x => <th className="text-start py-3 px-2" key={x}>{x}</th>)}</tr></thead><tbody>{ROLE_ACCESS_POLICIES[selected].modules.map(m => <tr key={m.path} className="border-b border-border-base/50"><td className="px-2 py-3 font-medium">{MODULE_NAMES[m.path]?.[ar ? 0 : 1]}</td><td className="px-2 py-3">{ar ? ({manage:'إجراءات محددة',review:'مراجعة محددة',view:'عرض'}[m.level]) : m.level}</td><td className="px-2 py-3">{ar ? ({organization:'المؤسسة ضمن اختصاصه',department:'قسمه فقط',self:'سجلاته فقط'}[m.scope]) : m.scope}</td></tr>)}</tbody></table></div><p className="text-xs text-text-secondary mt-4 leading-6">{ar ? 'الإدارة لا تعني كل الإجراءات. اعتماد الرواتب للمحاسب المفوّض فقط؛ الموظف لا يعتمد طلبه. الصحة لغير المختص: توصيات العمل المعتمدة فقط عند توفرها، لا الملف الطبي.' : 'Manage does not mean unrestricted actions. Only the delegated accountant approves payroll. No self-approval. Non-clinical health access means released work advice only, never medical records.'}</p></article></div>
    <aside className="border border-amber-200 bg-amber-50 rounded-xl p-5 text-sm leading-7">{ar ? 'سياسة مقترحة للنموذج التجريبي، تحتاج اعتماد إدارة المشفى وفق التفويض والقوانين المحلية. تسجيل الدخول باختيار الدور ليس حماية إنتاجية؛ يلزم خادم يفرض النطاق والصلاحيات وتدقيق دائم. المرجع الموسع داخل docs/hospital-role-research.ar.md.' : 'Proposed demo policy, subject to hospital delegation and local requirements. The role picker is not production authentication. Server-side authorization and durable audit are required. Research: docs/hospital-role-research.ar.md.'}</aside>
  </section>;
}
